
package vista;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 * MiniProyecto 4 - SuperMercado Univalle
 * @author Juan Sebastian Getial Getial <202124644>
 * @author Mauricio Muñoz Gutierrez <202123687>
 * @author Santiago Torres Carvajal <>
 * @profesor Luis Yovany Romo Portilla
 * Clase VentanaVenta
 */
public class VentanaVenta extends javax.swing.JFrame {

    DefaultTableModel modeloTabla = new DefaultTableModel();
    
    
    public VentanaVenta() {
        cargarModeloTabla();
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    public void cargarModeloTabla() {
        modeloTabla.addColumn("Produto");
        modeloTabla.addColumn("Precio (COP$)");
        modeloTabla.addColumn("Cantidad");
        modeloTabla.addColumn("Subtotal");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVenta = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        btnCancelarVenta = new javax.swing.JButton();
        btnAgregarAVenta = new javax.swing.JButton();
        btnEliminarItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        btnFinalizar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblProducto = new javax.swing.JLabel();
        cboxProductos = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenta.setText("Venta Actual");

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCategoria.setText("Categoría");

        btnCancelarVenta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCancelarVenta.setText("Cancelar Venta");

        btnAgregarAVenta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregarAVenta.setText("Agregar a Venta");

        btnEliminarItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEliminarItem.setText("Eliminar Item Seleccionado");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnFinalizar.setText("Finalizar");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Despensa", "Lacteos", "Enlatados", "Carnicos", "Frutas y verduras", "Delicatessen", "Licores", "Bebidas", "Snacks", "Limpieza", "Cuidado Personal", "Panaderia" }));

        lblProducto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblProducto.setText("Producto");

        cboxProductos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Total: $XXXXXXXX");

        btnSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSeleccionar.setText("Seleccionar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCancelarVenta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeleccionar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboxProductos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarAVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminarItem)
                        .addGap(33, 33, 33)
                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblVenta)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSeleccionar)
                        .addGap(18, 18, 18)
                        .addComponent(lblProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarAVenta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarItem)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarVenta)
                    .addComponent(btnFinalizar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVenta().setVisible(true);
            }
        });
    }
    
    public void agregarListenersBtns(ActionListener aL){
        btnAgregarAVenta.addActionListener(aL);
        btnCancelarVenta.addActionListener(aL);
        btnEliminarItem.addActionListener(aL);
        btnFinalizar.addActionListener(aL);
        btnSeleccionar.addActionListener(aL);
        jComboBox1.addActionListener(aL);
    }
    
    public void setCboxProductos(ArrayList<Producto> productos){
        limpiarComboBox();
        String categoria = (String)jComboBox1.getSelectedItem();
        for(Producto p : productos){
            if(p.getCategoria().equalsIgnoreCase(categoria) || 
                    categoria.equalsIgnoreCase("todos")){
                cboxProductos.addItem(p.getNombre());
            }
        }
    }
    
    public int getProductoSeleccionado(){
        return cboxProductos.getSelectedIndex();
    }
    
    public String getProductoElegido(){
        if(cboxProductos.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
            return "";
        }
        else{
            return (String)cboxProductos.getSelectedItem();
        }
    }
    
    public void setTablaCarrito(ArrayList<HashMap<String,String>> carrito){
        for(HashMap<String,String> p : carrito){
            int cantidad = Integer.parseInt(p.get("cantidad"));
            int presio = Integer.parseInt(p.get("precio"));
            int subTotal = cantidad * presio;
            Object[] fila = {p.get("nombre"), presio, 
                cantidad, subTotal};
            
            modeloTabla.addRow(fila);
        }
    }
    
    public void limpiarTablaCarrito(){
        int filas = jTable1.getRowCount();
        for(int i = filas -1; i >= 0; i--){
            modeloTabla.removeRow(i);
        }
    }
    
    public int getFilaTblCarrito(){
        int fila = jTable1.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "Seleccione un item");
        }
        return fila;
    }
    
    public ArrayList<String> getProductoInfo(int cualProducto){
        String nombre = (String) modeloTabla.getValueAt(cualProducto, 0);
        String cantidad = modeloTabla.getValueAt(cualProducto, 2).toString();
        
        ArrayList<String> info = new ArrayList<>();
        info.add(nombre);
        info.add(cantidad);
        return info;
    }
    
    public ArrayList<ArrayList<String>> getProductosInfo(){
        ArrayList<ArrayList<String>> productos = new ArrayList<>();
        
        for(int i = 0; i<jTable1.getRowCount(); i++){
            productos.add(getProductoInfo(i));
        }
        
        return productos;
    }
    
    public void setTotal(int total){
        lblTotal.setText("Total: "+ total);
    }
    
    private void limpiarComboBox(){
        cboxProductos.removeAllItems();
    }
    
    public boolean advertencia(){
        boolean estado = true;
        if(jTable1.getRowCount() == 0){
            estado = false;
            JOptionPane.showMessageDialog(null, "Agregue al menos un item");
        }
        else{
            JOptionPane.showMessageDialog(null, "Se registro la venta");
        }
        return estado;
    }
    
    public void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAVenta;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnEliminarItem;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cboxProductos;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVenta;
    // End of variables declaration//GEN-END:variables
}
